#!/bin/bash

if [ -x "/usr/sbin/sendmail" ]; then
  SENDMAIL="/usr/sbin/sendmail"
elif [ -x "/sbin/sendmail" ]; then
  SENDMAIL="/sbin/sendmail"
fi

#

if [ -n "$SENDMAIL" ]; then

  "$SENDMAIL" -t <<ERRMAIL
To: $1
From: systemd <root@$HOSTNAME>
Subject: $2
Content-Transfer-Encoding: 8bit
Content-Type: text/plain; charset=UTF-8

$(systemctl status --full "$2")
ERRMAIL

else

  echo "no sendmail found, aborting" 1>&2
  exit 1

fi

