#!/bin/bash

dockerid="$(docker ps | awk '$2=="ubuntu0" { print $1; }')"

#

[ $# != 0 ] || set -- bash

#exec docker exec -ti "$dockerid" bash
exec docker exec -ti "$dockerid" sh -c 'cd /root/fodexabgp-install; exec "$@"' -- "$@" 

