#!/bin/bash

echo "# exabgp:"
exabgpcli show neighbor summary
exabgpcli show neighbor extensive
exabgpcli show neighbor configuration
#exabgpcli show bgp ipv4 summary 
echo

echo "# bgpd:"
/usr/bin/vtysh -d bgpd -c "show ip bgp summary"
/usr/bin/vtysh -d bgpd -c "show ip bgp neighbors"
/usr/bin/vtysh -d bgpd -c "show ip bgp" # show routes
echo

echo "# bird:"
echo "show protocols all bgp1" | birdc
echo "show protocols all bgp2" | birdc
echo "show route all" | birdc

