#!/bin/bash

mkdir /run/quagga
chown quagga: /run/quagga

mkdir /var/log/quagga
chown quagga: /var/log/quagga

cat > /etc/quagga/zebra.conf <<EOF
! -*- zebra -*-
!
! zebra sample configuration file
!
! $Id: zebra.conf.sample,v 1.1 2002/12/13 20:15:30 paul Exp $
!
hostname Router
password zebra
enable password zebra
!
! Interface's description. 
!
!interface lo
! description test of desc.
!
!interface sit0
! multicast

!
! Static default route sample.
!
!ip route 0.0.0.0/0 203.181.89.241
!

log file /var/log/quagga/zebra.log
EOF

cat > /etc/quagga/daemons <<EOF
zebra=yes
bgpd=yes
EOF

##

set -x
#/usr/sbin/zebra -d -A 127.0.0.1 -f /etc/quagga/zebra.conf
exec /usr/sbin/zebra -A 127.0.0.1 -f /etc/quagga/zebra.conf "$@"



