#!/bin/bash

router_id="$1"
shift 1
myas="$1"
shift 1

echo "$0: router_id=$router_id myas=$myas" 1>&2

##

[ -n "$router_id" ] || router_id="10.0.0.1"

[ -n "$myas" ] || myas="9991"

##

mkfifo /run/exabgp.{in,out}
chmod 0600 /run/exabgp.{in,out}
chown exabgp: /run/exabgp.{in,out}

##

cat > /etc/exabgp/exabgp.conf <<EOF
#neighbor 10.0.0.2 {
#	router-id 10.0.0.1;
#	local-address 10.0.0.1;
#	local-as 9991;
#
#	peer-as 9992;
#
#	family {
#            ipv4 unicast;
#            ipv4 multicast;
#            ipv4 nlri-mpls;
#            ipv4 mpls-vpn;
#            ipv4 flow;
#            ipv4 flow-vpn;
#            ipv6 unicast;
#            ipv6 flow;
#            ipv6 flow-vpn;
#	}
#
#	static {
#		route 10.4.0.0/32 next-hop self;
#	}
#}
EOF

[ $# -gt 0 ] || set -- "10.0.0.3" "9993"

echo "$0: loop args: $*" 1>&2

while [ $# -gt 0 ]; do
  neighbor="$1"
  shift 1

  [ "$neighbor" != "--" ] || break

  neighborAS="$1"
  shift 1

cat >> /etc/exabgp/exabgp.conf <<EOF
#neighbor 10.0.0.3 
neighbor $neighbor {
	#router-id 10.0.0.1;
	router-id $router_id;
	#local-address 10.0.0.1;
	local-address $router_id;
	#local-as 9991;
	local-as $myas;

	#peer-as 9993;
	peer-as $neighborAS;

	#family {
	#    ipv4 unicast;
        #    #ipv4 multicast;
        #    #ipv4 nlri-mpls;
        #    #ipv4 mpls-vpn;
        #    #ipv4 flow;
        #    #ipv4 flow-vpn;
        #    #ipv6 unicast;
        #    #ipv6 flow;
        #    #ipv6 flow-vpn;
	#}

	static {
		route 10.10.0.0/32 next-hop self;
		route 10.100.0.0/32 next-hop self;
	}
}
EOF

done

##

if [ "$1" = "--bg" ]; then
  shift 1
  nohup exabgp --debug /etc/exabgp/exabgp.conf "$@" > exbgp.log 1>&2 &
else
  #/fod_vnet_router --mnexec h1 exabgp --debug /etc/exabgp/exabgp.conf
  exec exabgp --debug /etc/exabgp/exabgp.conf "$@"
fi

