#!/bin/bash

#if [ "$1" = "--inner.post" ]; then
#  shift 1
#
#  /fod_vnet_router --mnexec h1 /run-exabgp 10.0.1.1 9991  10.0.1.3 9993
#  /fod_vnet_router --mnexec r1 /run-bird2 --postfix 3 1.1.1.3 9993  10.0.1.1 9991 10.0.2.2 9992
#  /fod_vnet_router --mnexec h2 /run-bird2 --postfix 2 1.1.1.2 9992  10.0.2.3 9993

if [ "$1" = "--inner2.post" ]; then
  shift 1

  # ./exabgp/run-exabgp
  echo h1 /run-exabgp 10.0.1.1 9990    10.0.1.254 9991 -- --bg

  # ./exabgp/run-bird2
  echo r1 /run-bird2 --postfix 1 1.1.1.1 9991   10.1.12.2 9992   10.1.13.3 9993  10.0.1.1 9990
  echo r2 /run-bird2 --postfix 2 1.1.1.2 9992   10.1.12.1 9991   10.1.23.3 9993
  echo r3 /run-bird2 --postfix 3 1.1.1.3 9993   10.1.13.1 9991   10.1.23.2 9992

else 

  killall bird
  killall exabgp

  # ./vnet_router/fod_vnet_router
  # ./exabgp/custom-mn-topo2.py
  "/fod_vnet_router" "--init.sysstart.netconfd" --custom /custom-mn-topo2.py --topo mytopo --pre <("$0" --inner2.post)

fi





